import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./providers/ReduxProvider";
import { AppFooter } from "./widgets/AppFooter";
import { AppHeader } from "./widgets/AppHeader";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={`${nunito.variable} `}>
          <AppHeader />
          <main className="flex flex-col flex-auto">{children}</main>
          <AppFooter />
        </body>
      </ReduxProvider>
    </html>
  );
}
